name: helloworld
on: 
  push:
    branches:
      - master

jobs:
  hellowroldjob:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: | 
          echo "Hello World!"
   
          
