name: helloworld
on: 
  push:
    branches:
      - master

jobs:
  hellowroldjob:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: | 
          echo "Hello World!"
      - name: Say date
        run: echo date
      - name: Show me the path
        run: echo ls
      
          
